version: '3'
services:
  recruitment-test-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: recruitment-test-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/app/src
      - ./public:/app/public